spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/nutrition_db?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    url: ${DATASOURCE_URL:jdbc:mysql://mysql:3306/agent_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true}

    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:demo_pass_123}
  data:
    redis:
      host: localhost

# 生产环境日志级别
logging:
  level:
    root: WARN
    com.health.agent: INFO

